_BASE_: fc.yml
learning_rate: 0.00005
learning_rate_decay_start: -1
scheduled_sampling_start: -1

language_eval: 0
save_checkpoint_every: 3000
val_images_use: -1

batch_size: 10
max_epochs: 50
self_critical_after: 30
cached_tokens: f8k-train-idxs

train_sample_n: 5